server:
  port: 9091

spring:
  profiles:
    active: dev

  application:
    name: RESTAURANT-SERVICE

  datasource:
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
     ddl-auto: update
     format_sql: true
     use_sql_comments: true
    show_sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect



