server:
  port: 9092

spring:
  profiles:
      active: dev

  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    show_sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect



