server:
  port: 9093

spring:
  profiles:
    active: dev

  application:
    name: FOOD-CATALOGUE-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    show_sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect



