server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  #  profiles:
  #    active: dev

  application:
    name: FOOD-CATALOGUE-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/foodcataloguedb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    show_sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect



